import 'meal.dart';

Map<String, List<Meal>> mealsByCategory = {
  "Breakfast": [
    Meal("Oatmeal with Fruits", "Healthy, high fiber breakfast",
        ["Oats", "Milk", "Banana", "Strawberries", "Honey"],
        ["Boil oats", "Add fruits", "Serve"]),
    Meal("Egg & Avocado Toast", "High protein morning starter",
        ["Eggs", "Avocado", "Bread"],
        ["Toast bread", "Mash avocado", "Add eggs"]),
    Meal("Greek Yogurt Parfait", "A protein-packed, sweet breakfast that’s ready in minutes",
        [ "Greek Yogurt", "Mixed Berries", "Granola", "Honey"],
        ["Add yogurt to a bowl or cup", "Layer with berries", "Add granola on top", "Drizzle honey for sweetness"]),
  ],
  "Lunch": [
    Meal("Grilled Chicken Salad", "Light and protein-rich",
        ["Chicken Breast", "Lettuce", "Tomatoes", "Olive Oil"],
        ["Grill chicken", "Mix salad", "Add dressing"]),
    Meal("Brown Rice Veggie Bowl", "A balanced meal with carbs, healthy fats, and veggies",
        ["Cooked Brown Rice", "Broccoli", "Carrots", "Bell Peppers", "Soy Sauce", "Sesame Seeds"],
        ["Steam or sauté vegetables", "Add them to brown rice", "Drizzle soy sauce", "Top with sesame seeds"]),
    Meal("Whole Wheat Wrap", "A quick, healthy wrap perfect for lunch or school",
        ["Wheat Tortilla", "Hummus or Yogurt", "Lettuce", "Tomato Slices", "Cucumber", "Chicken or Beans"],
        ["Spread hummus on the tortilla", "Add veggies and chicken/beans", "Roll tightly and slice"]),
  ],
  "Dinner": [
    Meal("Salmon with Veggies", "Omega-3 rich dinner",
        ["Salmon", "Broccoli", "Carrots", "Lemon"],
        ["Bake salmon", "Steam veggies", "Serve together"]),
    Meal("Vegetable Stir Fry", "A fast and healthy meal with colorful vegetables",
        ["Broccoli", "Carrots", "Bell Peppers", "Mushrooms", "Soy Sauce", "Olive Oil"],
        ["Heat oil in a pan", "Add all vegetables", "Stir-fry for 5 minutes", "Add soy sauce and cook 1 more minute"]),
    Meal("Chickpea Curry", "A high-protein vegetarian dinner",
        ["Chickpeas", "Onion (chopped)", "Tomato (chopped)", "Curry Powder", "Salt and Pepper"],
        ["Sauté onions until soft", "Add tomato and curry powder", "Add chickpeas and mix well", "Cook for 10 minutes and serve with rice"]),
  ],
  "Snacks": [
    Meal("Fruit Smoothie", "Refreshing and energizing",
        ["Banana", "Berries", "Yogurt"],
        ["Blend all ingredients", "Serve chilled"]),
    Meal("Apple Slices With Peanut Butter", "A sweet, healthy snack rich in fiber and healthy fats",
        ["Apple", "Peanut Butter"],
        ["Slice the apple", "Dip slices in peanut butter"]),
    Meal("Mixed Nuts", "A nutritious snack that boosts energy",
        ["Almonds", "Walnuts", "Cashews"],
        ["Mix nuts in a small container", "Eat a handful (¼ cup)"]),
    Meal("Hummus With Carrots",  "A crunchy, satisfying snack high in protein and fiber",
        ["Hummus", "Carrot (cut into sticks)"],
        ["Wash and cut carrot into sticks", "Dip into hummus"]),
  ],
};